#ifndef INSTRUCONTROLLER_GLOBAL_H
#define INSTRUCONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INSTRUCONTROLLER_LIBRARY)
#  define INSTRUCONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define INSTRUCONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // INSTRUCONTROLLER_GLOBAL_H
